### ISSUE TITLE
AT Command Failure

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_BluefruitSPI#13]
I'm trying to run ghe bluefruitspi_simpletest with a feather_m4_express and Bluefruit SPI Friend and get this error
```Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-rc.0 on 2020-02-26; Adafruit Feather M4 Express with samd51j19
>>> import bluefruitspi_simpletest
Initializing the Bluefruit LE SPI Friend module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bluefruitspi_simpletest.py", line 19, in <module>
  File "adafruit_bluefruitspi.py", line 253, in command_check_OK
  File "adafruit_bluefruitspi.py", line 248, in command
  File "adafruit_bluefruitspi.py", line 248, in command
RuntimeError: AT command failure: RuntimeError('buffer size must match format',)
>>> 

```

the BlueFruit SPI Friend is running firmware 0.8.1 with latest CP 5.0 rc0 and libraries.

**Comment by jerryneedell** [comment]
this is apparently an issue with CP 5.0 -- it works with CP 4.x
comes from here https://github.com/adafruit/circuitpython/blame/master/shared-module/struct/__init__.c#L179

**Comment by jerryneedell** [comment]
looks like a simple ix -- I'll put in a PR
```
diff adafruit_bluefruitspi.py ~/projects/adafruit_github/Adafruit_CircuitPython_BluefruitSPI/adafruit_bluefruitspi.py 
182c182
<             msgtype, rspid, rsplen = struct.unpack('>BHB', self._buf_rx[0:4])
---
>             msgtype, rspid, rsplen = struct.unpack('>BHB', self._buf_rx)


```
